sudo: required

language: python

services:
  - docker
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - printenv | grep 'DATABASE_URL\|DJANGO_LOGFILE\|DJANGO_SETTINGS_MODULE\|SECRET_KEY\|DATASTORE_ACCESS_TOKEN\|DATABASE_URL\|TEST'
  - printenv | grep 'DATABASE_URL\|DJANGO_LOGFILE\|DJANGO_SETTINGS_MODULE\|SECRET_KEY\|DATASTORE_ACCESS_TOKEN\|DATABASE_URL\|TEST' >> ./env.list
  - docker build -t impactlab/oeem-energy-datastore .
  - docker run impactlab/oeem-energy-datastore --env-file ./env-list

script:
  - python manage.py test

