sudo: required

language: python

services:
  - docker
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - ./.travis-docker.sh

script:
  - python manage.py test

